### ISSUE TITLE
Compiled classes with no license information being misidentified as NOASSERTION

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#773] opened 2020-10-31 02:02 UTC
For details, see: https://github.com/clearlydefined/curated-data/pull/7662

![image](https://user-images.githubusercontent.com/17935946/97768739-86b6f380-1ae2-11eb-81c5-72892b1d6594.png)

**Comment by nellshamrell** [comment] 2021-01-05 21:12
While I do see this in production, it does not appear to have on dev.

To see, head to https://dev.clearlydefined.io/definitions/maven/mavencentral/org.apache.tomcat/coyote/6.0.51/6.0.51

Under "Files", expand "org", "apache", "jk", "core" and look at "MsgContext.class", "NOASSERTION" does not appear for it.

Checking the other similar issue.

**Comment by nellshamrell** [comment] 2021-01-05 21:16
Ah, the "other issue" is the pull request correcting this in the curated-data repo. 

Because this does not appear to be reproducible, I'm going to close this for now. It's possible this was a transient issue. However, if you see this again, *please* re-open this so we can gather more context and investigate further.

**Closed by nellshamrell** 2021-01-05 21:16 UTC
Labels: bug, reproducible
