### ISSUE TITLE
add proper validation on coordinates inputs for /harvest route

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#494] opened 2019-04-15 22:40 UTC
see the hack added https://github.com/clearlydefined/service/pull/492

getting coordinates like `maven/mavencentral/org.infinispan/infinispan-tree//1.2.3` should return an error to the caller instead of cleaning up the bad slashes for them

**Comment by ignacionr** [comment] 2019-06-13 16:21
The situation is reproducible on prod and dev, but not on local (where it fails even to reach the route, since the route is defined with a particular number of arguments not met with the additional slashes). On prod and dev, it seems to not matter the number of consecutive slashes inserted, they seem to end up as one. Leads me to believe this translation happens at a layer previous to hitting the service (such as at CDN handover).

**Comment by ignacionr** [comment] 2019-06-13 16:31
As per previous comment, we would need to inspect the corresponding CloudFlare rules active. Kindly advise.

**Comment by geneh** [comment] 2019-06-13 17:13
There are only two page rules:

1. api.clearlydefined.io/* Cache everything for two hours
1. www.clearlydefined.io/* Forwarding URL 301 - Permanent Redirect - https://clearlydefined.io/$1

Does it help?

**Comment by ignacionr** [comment] 2019-06-13 17:48
Yes it does. We still would maybe need a simple test like requesting and checking the logs.

My hypothesis is that the request sent gets changed before hitting dev or production; such test would prove it right or wrong.

On Jun 14, 2019, at 12:13 AM, Gene Hazan <notifications@github.com<mailto:notifications@github.com>> wrote:


There are only two page rules:

  1.  api.clearlydefined.io/*<http://api.clearlydefined.io/*> Cache everything for two hours
  2.  www.clearlydefined.io/<http://www.clearlydefined.io/>* Forwarding URL 301 - Permanent Redirect - https://clearlydefined.io/$1

Does it help?

**Comment by jeffmendoza** [comment] 2019-11-04 18:37
@ignacionr It would be good to follow up on this.

**Comment by ignacionr** [comment] 2019-11-27 10:08
@geneh  or @jeffmendoza can you take a look at this? As explained before, this is translated by the CDN...

**Comment by nellshamrell** [comment] 2021-01-04 18:12
@jeffmendoza any thoughts on this one or should I go ahead and close?

**Comment by nellshamrell** [comment] 2021-01-29 18:32
Closing for now, but if anyone has further thoughts on this please feel free to re-open.

**Closed by nellshamrell** 2021-01-29 18:32 UTC
Labels: enhancement
