### ISSUE TITLE
update swagger

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/service#238] opened 2018-09-21 04:47 UTC
The swagger for the service is now getting out of date as we updated the various schemas. Really need to figure out how to have swagger use the JSON schemas we are defining so there is one source of truth,

**Comment by moranthomas** [comment] 2018-10-12 11:16
I've used the schemas/curations.json and schemas/definitions.json to generate Swagger definition objects and this works but the issue is that the data defined in the json files here do not resemble the data in the yaml file at all so the output from the swagger looks completely different.
And there doesn't seem to be an automated way to migrate one from the other. Need a steer here.
Maybe there is another schema file you are using @jeffmcaffer or else we need some manual intervention to curate and get these 2 more closely aligned?

**Comment by jeffmcaffer** [comment] 2018-10-12 16:28
When you say they are "completely different" do you mean wrong or just the values and structures described are different? I would expect that the value are different, that't the point of this work, they diverged because they are maintained separately.

Perhaps put in a PR with the changes so people can run locally and see what you mean.

**Comment by moranthomas** [comment] 2018-10-15 14:20
Hey @jeffmcaffer. 
- I have tested with curation.json which works (see screenshot)
<img width="1268" alt="json swagger api-docs" src="https://user-images.githubusercontent.com/13868890/46956596-97c47180-d08d-11e8-9de7-af0452494cf0.png">

In this case you only have the model created in your api-docs so you lose all other information such as operations (see second screenshot of existing swagger api-docs generated from yaml) 
<img width="1262" alt="yaml swagger api-docs" src="https://user-images.githubusercontent.com/13868890/46956624-a579f700-d08d-11e8-81f2-652878caf809.png">

- We might need different URLs for each one if you want to go down this route but can investigate if wanted a way of generating only 1 url for all the JSON schema definitions.

**Comment by jeffmcaffer** [comment] 2018-10-15 15:57
Not sure why we lose the operations. Ideally the swagger could reference the json schema where it needs a type. For example., 

```yaml
  /curations/{type}/{provider}/{namespace}/{name}/{revision}:
    get:
      summary: Gets a curation for a component revision.
      tags:
        - curations
      parameters:
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/provider'
```

The `ref`s could reference `curation.json#defintions/provider` (or some such) rather than `#components/parameters/provider`

The swagger structure stays along with all the goodness of operations, and supporting descriptions etc. but all the data types come from the schemas.

Is that possible?

**Comment by moranthomas** [comment] 2018-10-16 15:15
Hey @jeffmcaffer . We are losing the operations as there is nothing in the schema/curation.json to reference them whereas the yaml has all of that extra information already.  
I think what you want is to be able to keep the existing yaml file and populate sections of that yaml with the extra information that is contained in the schemas (which are up to date) 
Unfortunately Swagger doesn't seem to support this concept as standard so we would have to create some custom code or scripts that would parse the json schemas and splice out only the parts we require, convert the json to yaml definitions and then programmatically append this in the correct location in the yaml file.
So while possible not straightforward...

**Comment by jeffmcaffer** [comment] 2018-10-16 16:08
This is confusing. The swagger doc (https://swagger.io/docs/specification/2-0/describing-request-body/) seems to indicate that you can `$ref` bodies (for example). Similarly, `$ref`s can be external files. So these together should work. The OpenAPI 3.0 doc is even more explicit about this in 

* https://swagger.io/docs/specification/describing-request-body/
* https://swagger.io/docs/specification/using-ref/

If we have to move to the OpenAPI 3.0 that can be considered.

For example, I tried this in the swagger.yaml. did not work directly but I could just have the path wrong or we need to actually surface the referenced files in a route. (it is unclear when the `$ref` is resolved, at startup/config time or at runtime from the UI.) I've not had time to mess around with different ref paths/urls.

```yaml
  /curations/{type}/{provider}/{namespace}/{name}/{revision}:
    patch:
      summary: Patches the curation of a component revision.
      tags:
        - curations
      parameters:
        - in: body
          schema:
            - $ref: '../schemas/curation.json#/definitions/revisions'
      responses:
        200:
          description: Nothing. TODO - this should be 204 or return something.
```

**Comment by AlexWebYourmind** [comment] 2018-10-17 14:08
@jeffmcaffer could it be that your test was on a GET request, which does not allow requestBody to be specified? requestBody is not allowed for GET reuquests. Can you confirm that for those we should actually aim to describe the response? (https://swagger.io/docs/specification/describing-responses/)

**Comment by moranthomas** [comment] 2018-10-17 17:15
Couple of updates/notes 
1. First a question - It looks as though we are already using OpenAPI 3.0 as specified in the swagger.yaml - correct?
2. With the GET example it fails initially with a yaml exception. As pointed out by Alex we should be able to use GET by using the ResponseBody $ref instead of the RequestBody $ref for this
3. Using POST gets past this initial issue in testing but now we get a new error: Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: '../schemas/curation.json' basePath: 'undefined'. Tried a number of things to try and resolve including trying to modify basePath but only thing that got rid of the error seemed to be an upgrade to latest swagger-ui-express. 
4. Currently no errors on load but the model is not getting populated with the data (See screenshot) 
5. Still investigating possible solutions, WIP PR available here - https://github.com/WebYourMind/service/pull/4

**Comment by jeffmcaffer** [comment] 2018-10-18 04:41
Answers/comments:
1. perhaps. I thought not but sure.
2. my example was for a PATCH. we should use the right syntax to match the method.
3. If I understand, updating the swagger infra fixes the problem? awesome
4. It seems that the the $ref path gets resolved by the ui in the user's browser. that MAY mean that we need to have a static file route that serves up the schema files in $ref.

**Comment by moranthomas** [comment] 2018-11-05 16:38
Just an fyi - 
So yes upgrading the infra gets us further and we don't get errors however we the I tried setting up a static route for this in the service layer but not resolving the issue around blank json data coming back.

As you point out it may be that the path is being resolved in the swagger-ui-express node module and I haven't broken that out and debugged into it internally yet. 

I have put the status of this in a blocked state

**Closed** 2018-11-20 23:59 UTC
Labels: good first issue, help wanted
