### ISSUE TITLE
UI is not displaying license information

### ISSUE THREAD

**Issue by royaljust** [clearlydefined/service#550] opened 2019-06-07 16:44 UTC
When I go to [this link](https://clearlydefined.io/definitions/git/github/ms-iot/edk2/8594c2073cdb1065e60f01e9b099918c5e839212), I get no license information.

![image](https://user-images.githubusercontent.com/36014796/59119836-b0c5af80-8908-11e9-9e05-020cd7a6ce2b.png)

Then, only after I click to curate the declared license, all the license information appears.

![image](https://user-images.githubusercontent.com/36014796/59119904-dd79c700-8908-11e9-935e-b516690bb04e.png)

**Comment by pombredanne** [comment] 2019-06-07 21:31
Here is my flow:
1. Go to https://clearlydefined.io/definitions/git/github/ms-iot/edk2/8594c2073cdb1065e60f01e9b099918c5e839212
It looks like this
![1](https://user-images.githubusercontent.com/675997/59134561-e22b9300-897b-11e9-9602-cb0b474365b2.png) 

 Note the absence of scancode in the listed tools.

2. As you see there is no license for the "AArch64.h" file

3. I click on the edit button for AArch64.h and then pick some license, any one. As soon as this happens all the license show up for all the files.



(and the scancode scan data are there alright in the harvest tab too)
![4](https://user-images.githubusercontent.com/675997/59134585-f7082680-897b-11e9-8e85-4ccc7ce779e9.png)

**Comment by pombredanne** [comment] 2019-06-07 21:32
So I do not know where the issues comes from, but there is a a clear issue of the "harvested" data being out of sync with the UI listing that data.

**Comment by geneh** [comment] 2019-06-10 15:27
MongoDB `db.getCollection('definitions-paged').findOne({'_id': 'git/github/ms-iot/edk2/8594c2073cdb1065e60f01e9b099918c5e839212' })`:
```
        "tools" : [ 
            "clearlydefined/1.3.0", 
            "licensee/9.13.0"
        ],
```
Definitions blob storage:
```
"tools":["clearlydefined/1.3.0","licensee/9.13.0"]
```
Crawler's blob storage:
<img width="762" alt="Screen Shot 2019-06-10 at 8 23 57 AM" src="https://user-images.githubusercontent.com/1537662/59206178-40fa3380-8b59-11e9-83a5-95a84530ba69.png">
The size of tool/scancode/3.2.2.json is 15.3 MB.

**Comment by fossygirl** [comment] 2019-09-05 19:24
@ignacionr Can you look into this?

**Comment by ignacionr** [comment] 2019-09-23 09:38
@geneh I have been looking into this and it doesn't seem to reproduce on a test package; do you believe this may be related to the size of the existing data on Mongo? If there's a way you can copy this data point from the production MongoDB into the DEV environment, there's chances I will be able to reproduce, do you agree?

**Comment by geneh** [comment] 2019-09-23 19:47
It looks like there is no issue with https://clearlydefined.io/definitions/git/github/ms-iot/edk2/8594c2073cdb1065e60f01e9b099918c5e839212 anymore. All three tools appear in the UI, definition store, and MongoDB.
The declared license is now BSD-2-Clause-Patent and there are no curations.
Can this issue be closed?

**Comment by ignacionr** [comment] 2019-10-01 15:51
Closing for the time being. Please reopen if the issue reappears.

**Closed by ignacionr** 2019-10-01 15:51 UTC
Labels: bug
