### ISSUE TITLE
Need to update where we point to Maven packages

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#707] opened 2020-02-28 19:58 UTC
We decided to point to http://central.maven.org/maven2 for Maven packages, but this URL isn’t working anymore (for the history, see -  https://github.com/clearlydefined/service/issues/588).

We need to fix where mavens will point to for the package.

Cc. @pombredanne ; @geneh

**Comment by pombredanne** [comment] 2020-02-29 03:34
@ariel11 Thanks... Historically this has been https://repo1.maven.org/maven2/ 
I am asking the Maven folks for clarity there

**Comment by ariel11** [comment] 2020-02-29 17:49
> @ariel11 Thanks... Historically this has been https://repo1.maven.org/maven2/
> I am asking the Maven folks for clarity there

Thank you for checking @pombredanne!  Really appreciate it.

When I look at what ClearlyDefined is using now, it seems to be that central.maven link, which is not working - e.g .https://clearlydefined.io/definitions/maven/mavencentral/org.ow2.asm/asm-util/6.0. 
![image](https://user-images.githubusercontent.com/17935946/75612487-b091c380-5ad8-11ea-9c8f-e0a586b87372.png)

**Comment by ariel11** [comment] 2020-03-24 21:45
@pombredanne / @jeffmendoza - all of our maven packages in ClearlyDefined have broken links - if you click on the package version or the source link.  Can we please get this fixed? 

For example, this is the "Source" link http://central.maven.org/maven2/com/vaadin/vaadin-server/8.10.0/vaadin-server-8.10.0-sources.jar for https://clearlydefined.io/definitions/maven/mavencentral/com.vaadin/vaadin-server/8.10.0.  That "Source" link (and all links using that format) are broken. 

I can find the sources jar here: https://repo1.maven.org/maven2/com/vaadin/vaadin-server/8.10.0/. 

@pombredanne - is it correct to repoint all our http://central.maven.org/maven2/com.....URL's to https://repo1.maven.org/maven2/com....?

**Comment by jeffmendoza** [comment] 2020-07-23 16:50
Fixed by #754

**Comment by pombredanne** [comment] 2020-07-24 05:24
@disulliv @jeffmendoza https://search.maven.org/remotecontent?filepath=com/fasterxml/jackson/module/jackson-module-scala_2.11/2.11.1/jackson-module-scala_2.11-2.11.1-sources.jar is not the correct download URLs for maven JARs 

This is the page where this is documented:
http://maven.apache.org/ref/current/maven-model-builder/super-pom.html

https://repo.maven.apache.org/maven2 is the one we need.

**Comment by ariel11** [comment] 2020-11-02 21:33
See also: https://github.com/clearlydefined/website/issues/864,
https://github.com/clearlydefined/service/issues/755,

**Comment by nellshamrell** [comment] 2021-01-05 22:18
Closing as duplicate of #755

**Closed by nellshamrell** 2021-01-05 22:18 UTC
Labels: bug, duplicate
