### ISSUE TITLE
Missing curated data, possible bug

### ISSUE THREAD

**Issue by peggymoloney** [clearlydefined/service#574] opened 2019-06-26 16:21 UTC
May have found a bug - Declared license field blank https://clearlydefined.io/definitions/nuget/nuget/-/WindowsAzure.Storage/2.1.0

Curated here (https://clearlydefined.io/curations/1192)

![image](https://user-images.githubusercontent.com/29741356/60197109-9f7b0f00-97f3-11e9-929f-79fff529ec67.png)

**Comment by ignacionr** [comment] 2019-06-27 13:55
We are looking at revision 2.1.0 (which we never harvested) at https://clearlydefined.io/definitions/nuget/nuget/-/WindowsAzure.Storage/2.1.0 ; the curation of reference https://github.com/clearlydefined/curated-data/pull/1192 affects revision 9.2.0 (makes it Apache-2) but then got superseded by https://github.com/clearlydefined/curated-data/pull/1736 which makes it MIT as you can check at https://clearlydefined.io/definitions/nuget/nuget/-/WindowsAzure.Storage/9.2.0

How did we get to checking revision 2.1.0?

What we could do is return a different kind of response for unknown revisions such as this. Just a thought.

**Comment by ignacionr** [comment] 2019-06-27 16:41
@peggymoloney can you let us know if there is still something to take a look at here? Appreciated.

**Comment by peggymoloney** [comment] 2019-06-27 18:02
@ignacionr Interesting, why is the #1192 even showing up in the 2.1.0 component since it doesn't reference it???  We got the request to curate it when someone was trying to print the Notice file.  Let me see i can actually find the license.  But bigger question, why was #1192 attached to 2.1.0, that must be a bug....

**Comment by royaljust** [comment] 2019-06-28 15:30
@ignacionr - I'm having a issue here that potentially has the same root cause: https://clearlydefined.io/definitions/nuget/nuget/-/jquery/1.10.2  

You'll note that the curation was merged but the component is still reading as no assertion.

**Comment by ignacionr** [comment] 2019-06-28 16:39
@royaljust actually this seems to be an example of a more valid issue (in the previous one, we were curating one revision and expecting it to change a different one). Let me check this other one.

**Comment by ignacionr** [comment] 2019-06-28 16:48
@peggymolone I would need to check, but my belief is that curations are shown for all revisions of the same component. Filtering them would be complex and the feature of not seeing curations that affect the same package doesn’t appeal much to me. I will though take this to the Monday meeting for the team to give it a thought, since I may be missing something and also all help and ideas are appreciated.

**Comment by peggymoloney** [comment] 2019-07-09 22:21
@ignacionr Have you had a chance to check on this?

**Comment by ignacionr** [comment] 2019-07-10 00:48
@peggymonoley as expressed before, it’s more if we want such feature than checking. Can you put in words what difficulties as a curator that this brings you? Honestly, I believe we would lose the chance to see other curations that may have leads to help your work.

**Comment by ignacionr** [comment] 2019-07-10 13:36
@peggymoloney we've been discussing it with @storrisi and we want to bring it to the community; we understand from your point of view it's confusing to see revisions that you're not interested in. Also as an API it would look like we need to filter it out.
As for @royaljust we need to create a separate issue, since they're not related.

**Closed** 2019-08-05 03:58 UTC
Labels: bug
