### ISSUE TITLE
CI not running all tests

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/service#201] opened 2018-08-17 22:38 UTC
noticed this in https://github.com/clearlydefined/service/pull/198

there are 95 tests running locally, but only 64 running on Travis

![image](https://user-images.githubusercontent.com/5168796/44291496-8a2c7000-a233-11e8-924b-161db9d4e0d2.png)
![image](https://user-images.githubusercontent.com/5168796/44291500-91ec1480-a233-11e8-9c1f-1f8aaedf9c0c.png)

**Comment by jeffmcaffer** [comment] 2018-08-25 22:12
Numbers have changed (more tests! yay) but the problem is still there. There is also one test that fails on travis but runs fine on my windows machine. 

  84 passing (247ms)
  1 failing
  1) Webhook Route for GitHub calls
       handles closed event that is merged:
      AssertionError: expected false to be true
      + expected - actual
      -false
      +true
      
      at Context.it (test/routes/webhookGitHubTests.js:62:63)
      at <anonymous>

**Closed** 2018-11-19 21:00 UTC
