### ISSUE TITLE
Some curations submitted via the website are marked as invalid

### ISSUE THREAD

**Issue by joseharriaga** [clearlydefined/service#564] opened 2019-06-17 22:21 UTC
I submitted a few curations via clearlydefined.io that were marked as "invalid curations" by the PR bot. There's no explanation as to why they are invalid or how I can resolve them. Is there something I'm doing wrong? Here's the curations I'm referring to:

Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.0
https://github.com/clearlydefined/curated-data/pull/2034

Microsoft.IdentityModel.Clients.ActiveDirectory/4.5.1
https://github.com/clearlydefined/curated-data/pull/2039

CommandLineParser/2.4.3 
https://github.com/clearlydefined/curated-data/pull/1987

Moq/4.10.1
https://github.com/clearlydefined/curated-data/pull/1974

StackExchange.Redis.StrongName/1.2.6
https://github.com/clearlydefined/curated-data/pull/1984

**Comment by geneh** [comment] 2019-06-18 21:57
The error is coming from https://github.com/clearlydefined/service/blob/3c50a31aeccafcf2dad17032f0ea3809947edd53/providers/curation/github.js#L138
Every time a curation PR is opened, a webhook is fired and curation-prod-webhook logic app is putting the message as is on curations queue which is polled by the service every 30 sec.
@ignacionr, could you please check why these curations are marked as invalid?

**Comment by ignacionr** [comment] 2019-06-19 17:18
By analyzing in depth the case of https://github.com/clearlydefined/curated-data/pull/2034 with its curation I find that the problem for the system is that even thought the curation made to revision 4.5.0 is valid, the result of merging it still leaves [revision 3.13.9](https://github.com/clearlydefined/curated-data/blob/f38fc9b5eec12ee2f838c0d537299001502de72f/curations/nuget/nuget/-/Microsoft.IdentityModel.Clients.ActiveDirectory.yaml#L20) with an invalid ```sourceLocation``` (i.e. it lacks the ```name```).

What do we want to do in similar cases? I find the topic to be of interest.

**Comment by ignacionr** [comment] 2019-06-19 17:27
Also https://github.com/clearlydefined/curated-data/pull/2039 has a pre-existing version with an [invalid sourceLocation](https://github.com/clearlydefined/curated-data/blob/c99b7cba9ac4d167151cc7bf9dc0e8121b24b0b7/curations/nuget/nuget/-/Microsoft.IdentityModel.Clients.ActiveDirectory.yaml#L20) -no ```name```.

**Comment by ignacionr** [comment] 2019-06-19 17:29
https://github.com/clearlydefined/curated-data/pull/1987 also has an [invalid ```sourceLocation```](https://github.com/clearlydefined/curated-data/blob/066eaf97419e1909d4688de8f33bcd8d49b7c36f/curations/nuget/nuget/-/CommandLineParser.yaml#L9)

**Comment by ignacionr** [comment] 2019-06-19 17:47
https://github.com/clearlydefined/curated-data/pull/1974 has four invalid ```sourceLocation``` objects starting with [this one](https://github.com/clearlydefined/curated-data/blob/e21519f6c071b1bca3d8c837aab6bf0adb3ee957/curations/nuget/nuget/-/Moq.yaml#L15)

**Comment by ignacionr** [comment] 2019-06-19 17:48
https://github.com/clearlydefined/curated-data/pull/1984 also suffers from a pre-existing [invalid ```sourceLocation```](https://github.com/clearlydefined/curated-data/blob/74485101614d55b564a7425de707a6b1640634e8/curations/nuget/nuget/-/StackExchange.Redis.StrongName.yaml#L9)

**Comment by ignacionr** [comment] 2019-06-19 18:18
@joseharriaga the checks that fail are not preventing a merge, can you go on and try merge one of these, see if the result is as expected? In the meantime, we will add an additional validation before the PR creation so to let you know in advance of possible issues with the baseline curations.

**Comment by joseharriaga** [comment] 2019-06-19 18:47
Thanks, @ignacionr. Let me ask the curators if they can try to merge these. 

To make sure I understand: It seems like the file has pre-existing errors, which means that any curations to these components will be marked as invalid no matter what, correct? Should we try to fix these files? For example, for [revision 3.13.9 of Microsoft.IdentityModel.Clients.ActiveDirectory](https://github.com/clearlydefined/curated-data/blob/f38fc9b5eec12ee2f838c0d537299001502de72f/curations/nuget/nuget/-/Microsoft.IdentityModel.Clients.ActiveDirectory.yaml#L20), the source location seems to be missing "name" and "namespace", which are supposed to be "azure-activedirectory-library-for-dotnet" and "AzureAD" respectively. Do you think adding these would fix the issue?

**Comment by ignacionr** [comment] 2019-06-19 19:16
You got it right, yes.

**Comment by ignacionr** [comment] 2019-06-20 02:49
Since it looks like the check for validity was already there (thus this situation shouldn't have happened), I will try to see if the issue can be reproduced. The code that does the check is https://github.com/clearlydefined/service/blob/d3d1eacc17efbe27b03bd333d2b22629a73b2b9c/routes/curations.js#L78

**Comment by pombredanne** [comment] 2019-06-20 09:26
@ignacionr what would be great is to provide feedback either in the UI or in the PR that there are some issues.

**Comment by ignacionr** [comment] 2019-06-20 09:47
Well @pombredanne the code is there, and it shouldn't even allow you to create the PR; I need to figure out why it didn't run for those cases.

**Comment by geneh** [comment] 2019-06-20 16:14
Could it be because of the fairly recent move from using curations API to curations queue? The GitHub webhook point to a logic app that puts messages on curations queue.

**Comment by geneh** [comment] 2019-06-20 17:01
If that's the case, can we add more logging and a more descriptive check message, so it's easier for us to troubleshoot and for users to know what the problem is?

**Comment by ignacionr** [comment] 2019-06-21 16:46
It may be the reason. Still I don't think that the PR can be created within our app without going through validation. Still checking this.

**Comment by geneh** [comment] 2019-06-21 17:23
Okay, we should add more logging in any case. @ignacionr, could you please also check how many yaml files in https://github.com/clearlydefined/curated-data have incorrect schema like the missing name and namespace under sourceLocation? For example, I was able to manually fix https://github.com/clearlydefined/curated-data/pull/2060. I think we should proactively fix all the problematic yaml files.

**Comment by ignacionr** [comment] 2019-06-27 17:03
We agreed to take a look at the number of issues like this that are outstanding (a simple tool may be able to do this).

**Comment by ignacionr** [comment] 2019-07-17 16:27
The issue was resolved by creating a tool that lead to the submission of https://github.com/clearlydefined/curated-data/pull/2214 with all schema upgrades required.

**Closed by ignacionr** 2019-07-17 16:27 UTC
Labels: bug
