### ISSUE TITLE
Definitions API fails while using the Browse Page

### ISSUE THREAD

**Issue by storrisi** [clearlydefined/service#401] opened 2019-02-15 15:41 UTC
While navigating the Browse Page on the UI, any kind of call to the `definitions` endpoint, fails with a 500 error.

See https://dev-api.clearlydefined.io/definitions

**Comment by dabutvin** [comment] 2019-02-15 16:18
weird that this just started happening out of nowhere. I'll look into this today

**Comment by dabutvin** [comment] 2019-02-15 17:31
I've tracked this down to the 'sort' parameter. Still doesn't explain why it started failing with no other changes. I am seeing it intermittently work too which is stranger

**Comment by dabutvin** [comment] 2019-02-15 18:41
Really stumped. I ended up opening a support ticket

This is the error:

The provided cross partition query can not be directly served by the gateway. This is a first chance (internal) exception that all newer clients will know how to handle gracefully. This exception is traced, but unless you see it bubble up as an exception (which only happens on older SDK clients), then you can safely ignore this message.

**Comment by dabutvin** [comment] 2019-02-19 17:43
The support ticket was resolved by the database team by reverting a recent change.
Everything is working as intended now. That was weird

**Closed by dabutvin** 2019-02-19 17:43 UTC
