### ISSUE TITLE
Discovered license in LICENSE.txt in root of repository did not populate declared license

### ISSUE THREAD

**Issue by iamwillbar** [clearlydefined/service#559] opened 2019-06-14 20:46 UTC
In this repository we found Apache-2.0 with high confidence in the LICENSE.txt but did not populate the declared license on the definition:
https://clearlydefined.io/definitions/git/github/davidebbo/webactivator/8a21247a5bdc61af3077bafceac602a9cb236875

**Comment by jeffmendoza** [comment] 2019-11-04 18:51
Re-harvest with latest versions and see if still an issue.

**Comment by jeffmendoza** [comment] 2019-11-07 18:19
Re-harvested with the same issue.

**Comment by nellshamrell** [comment] 2021-01-07 20:04
Queued up a harvest in our dev environment to confirm there.

[(dev) webactivator](https://dev.clearlydefined.io/definitions/git/github/davidebbo/webactivator/8a21247a5bdc61af3077bafceac602a9cb236875)

**Comment by nellshamrell** [comment] 2021-01-16 00:12
Closing as a duplicate of #759 and consolidating discussion there.

**Closed by nellshamrell** 2021-01-16 00:12 UTC
Labels: bug
